### PR TITLE
Remove kops install; default helm is now helm3; update README

### PR DESCRIPTION
**Pull request by mbacchi**
Kops is no longer necessary

Helm2 is deprecated, make helm3 default `helm` command

### CODE REVIEW

**Review by bhb603 — APPROVED** [review]
Awesome.. I can't test because I dont have this Ansible setup, but LGTM.

Want to remove `kops` from the MacOS bootstrap as well? Should just be deleting these two lines:
https://github.com/codecademy-engineering/bootstrap/blob/23f2c74e6ad292eefe326266829313e36a8c5423/files/Brewfile#L59-L60

**Comment by mbacchi** [comment]
> Awesome.. I can't test because I dont have this Ansible setup, but LGTM.
> 
> Want to remove `kops` from the MacOS bootstrap as well? Should just be deleting these two lines:
> https://github.com/codecademy-engineering/bootstrap/blob/23f2c74e6ad292eefe326266829313e36a8c5423/files/Brewfile#L59-L60

All set, mind re-reviewing?

**Review by bhb603 — APPROVED** [review]

**Comment by fisxoj** [comment]
Just got around to running this - it appears my unversioned helm command points to helm2, which sounds different than the desired outcome:
```
❯ helm version                                                                                                                                                                            
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

```

**Comment by mbacchi** [comment]
I chatted with @fisxoj and will work on making this more idempotent. I will open an issue now to track this.

**Pull request merged**
