### PR TITLE
Pin kubectl to v1.23.6

### PR DESCRIPTION
**Pull request by mbacchi**
Remove mongodb repo on linux (due to version/library problems for somewhere around a year)

(Asking Daniel to test the brew version pinning to see if it works on Mac.)

### CODE REVIEW

**Comment by dantech2000** [comment]
Script fails to install the pinned version of kubectx@1.23.6,
`Installing kubectx@1.23.6
Warning: 'kubectx@1.23.6' formula is unreadable: No available formula with the name "kubectx@1.23.6". Did you mean kubectx?
Warning: No available formula with the name "kubectx@1.23.6". Did you mean kubectx?
==> Searching for similarly named formulae...
This similarly named formula was found:
kubectx
To install it, run:
  brew install kubectx
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
Installing kubectx@1.23.6 has failed!
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
Check for differences in your Brewfile.lock.json!
`

**Comment by mbacchi** [comment]
> With the changes made, bootstrap will install kubernetes-cli@1.22 and append the export to the PATH variable. In Ana's case she'll need to uninstall `brew uninstall kubectx` && `brew uninstall kubectl` then rerun bootstrap script.

Interesting, didn't realize kubernetes-cli was the same as kubectl. Looks good to me if it works on Mac. I'd maybe ask @anaharris to test and potentially a couple other folks too to verify it will be fine generally across the board.

**Review by anaharris — COMMENTED** [review]
I uninstalled `kubectx` and `kubectl` (had to use `brew uninstall --ignore-dependencies kubectl`). At first I got several errors and most were fixed after I ran commands suggested in the error message (`rm '/usr/local/bin/kubectl'`, `rm '/usr/local/bin/aws_completer'`, `rm '/usr/local/bin/go'`). Kube stuff seems to have been installed successfully, I just got a couple other errors, not sure if they're relevant here:
```
Error: Could not symlink bin/go
Target /usr/local/bin/go
already exists. You may want to remove it:
  rm '/usr/local/bin/go'

To force the link and overwrite all conflicting files:
  brew link --overwrite go

To list all files that would be deleted:
  brew link --overwrite --dry-run go
Linking /usr/local/Cellar/go/1.18.4...

...

Installing session-manager-plugin
Password:
==> Downloading https://s3.amazonaws.com/session-manager-downloads/plugin/1.2.339.0/mac/session-manager-plugin.pkg
Already downloaded: /Users/anaharris/Library/Caches/Homebrew/downloads/66aa95b4fe73601081e912d67bf94d68940c6eed637f9adcf27c2b79ebcd9413--session-manager-plugin.pkg
==> Installing Cask session-manager-plugin
==> Running installer for session-manager-plugin; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Error: It seems there is already a Binary at '/usr/local/bin/session-manager-plugin'.
installer: Package name is session-manager-plugin
installer: Upgrading at base path /
installer: The upgrade was successful.
==> Purging files for version 1.2.339.0 of Cask session-manager-plugin
Installing session-manager-plugin has failed!

...

Homebrew Bundle failed! 1 Brewfile dependency failed to install.
```

**Review by dantech2000 — APPROVED** [review]
Tested and LGTM 👍

**Pull request merged**
