### PR TITLE
Install Hashicorp repo and packer

### PR DESCRIPTION
**Pull request by mbacchi**

### CODE REVIEW

**Review by callafeucht — COMMENTED** [review]
Does anyone outside of the I&S team need packer? Also, if we're going to include its installation for Linux workstations, should we also include it for Mac?

**Comment by mbacchi** [comment]
> Does anyone outside of the I&S team need packer? Also, if we're going to include its installation for Linux workstations, should we also include it for Mac?

We also install tfenv, and I doubt anyone outside I&S requires that. Maybe we could setup a flag or a script that is used by I&S specifically (for both brew and ansible.) It's easy to do in ansible, just separate the infra and non-infra tools into different yml files. Same with brew I imagine, we could create a separate shell script to run.

I'm not too worried though about having folks install packer (or tfenv) who may not use it. I would rather favor simplicity over granular support for devs/infra team members. If we had huge packages that needed to be installed for the infra team only then we might want to do such a thing. I dunno, I'm open to ideas.

**Comment by callafeucht** [comment]
> > Does anyone outside of the I&S team need packer? Also, if we're going to include its installation for Linux workstations, should we also include it for Mac?
> 
> We also install tfenv, and I doubt anyone outside I&S requires that. Maybe we could setup a flag or a script that is used by I&S specifically (for both brew and ansible.) It's easy to do in ansible, just separate the infra and non-infra tools into different yml files. Same with brew I imagine, we could create a separate shell script to run.
> 
> I'm not too worried though about having folks install packer (or tfenv) who may not use it. I would rather favor simplicity over granular support for devs/infra team members. If we had huge packages that needed to be installed for the infra team only then we might want to do such a thing. I dunno, I'm open to ideas.

I didn't even realize we were installing tfenv for all users. TIL. Agreed, I don't want to overcomplicate the bootstrapping process. I think adding a flag for I&S folks is a great idea!

**Review by callafeucht — APPROVED** [review]

**Comment by mbacchi** [comment]
> I didn't even realize we were installing tfenv for all users. TIL. Agreed, I don't want to overcomplicate the bootstrapping process. I think adding a flag for I&S folks is a great idea!

I think what I'll do here today (because I'm trying to get to a couple other tasks) is to open an issue to add a flag or a separate ansible playbook that would only be used by I&S. That issue can be worked on when time allows, as for now this works it just adds software to developers laptops that they might not ordinarily use. Does that work @callafeucht?

**Comment by callafeucht** [comment]
> I think what I'll do here today (because I'm trying to get to a couple other tasks) is to open an issue to add a flag or a separate ansible playbook that would only be used by I&S. That issue can be worked on when time allows, as for now this works it just adds software to developers laptops that they might not ordinarily use. Does that work @callafeucht?

Absolutely! Sorry for the implied scope creep 😅  a dedicated ticket for this makes perfect sense.

**Pull request merged**
